# Generated by Django 4.0.10 on 2023-09-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prom_endpoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promendpoint',
            name='name',
        ),
        migrations.AlterField(
            model_name='promendpoint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promendpoint',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
