# Generated by Django 4.0.10 on 2023-09-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prom_endpoint', '0002_remove_promendpoint_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MimirEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tenantId', models.CharField(max_length=100)),
            ],
        ),
    ]
